### PR TITLE
Code review

### LINKED ISSUE #28: Does not opens file...

### PR DESCRIPTION
**Pull request by ldez**
- use Disposables
- use notification for errors
- add CI configurations (you must activate CI in [Travis CI](https://travis-ci.org) and [AppVeyor](https://ci.appveyor.com))
- add CoffeeLint configuration
- use Opn (don't reinvent the wheel)
- works with standard Atom and Nuclide
- fix keymaps bindings and change to <kbd>ctrl-shift-q</kbd> and <kbd>cmd-shift-q</kbd> on OSX

Fix #28, #26, #25, #23, #21

### CODE REVIEW

**Comment by ldez** [comment]
Any remarks ?

**Comment by magbicaleman** [comment]
@ldez thank you for your contribution. I've only glanced it, but I'll be looking at it soon.

**Comment by ldez** [comment]
@magbicaleman now you can activate CI with [Travis CI](https://travis-ci.org) and [AppVeyor](https://ci.appveyor.com)
Can you publish a new version ?

**Comment by magbicaleman** [comment]
I have Travis CI activated ([failed](https://travis-ci.org/magbicaleman/open-in-browser/builds/219439002)), not yet with AppVeyor. I'm assuming the AppVeyor CI, is to test out the plugin in the windows environment.

**Pull request merged**
